# Generated by Django 3.2.11 on 2022-01-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('bikeId', models.PositiveIntegerField()),
                ('location_lat', models.DecimalField(decimal_places=8, max_digits=12)),
                ('location_lon', models.DecimalField(decimal_places=8, max_digits=12)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=4)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=6)),
                ('gaz1', models.DecimalField(decimal_places=2, max_digits=6)),
                ('gaz2', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
