# Generated by Django 3.2.10 on 2022-01-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicloud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensordata',
            old_name='bikeId',
            new_name='bikeid',
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='temperature',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
